export const leagues = {
  ENG_1: 'Premier League',
  ENG_2: 'Championship',
  ENG_3: 'League 1',
  ENG_4: 'League 2',
  FR_1: 'Ligue 1',
  FR_2: 'Ligue 2',
  GER_1: 'Bundesliga',
  GER_2: '2. Bundesliga',
  GER_3: '3. Bundesliga',
  SPA_1: 'La Liga',
  SPA_2: 'Segunda División',
  ITA_1: 'Serie A',
  ITA_2: 'Serie B',
  SWE_1: 'Allsvenskan',
  BEL_1: 'Pro League',
  CHI_1: 'Chilean Primera División',
  CZE_1: 'Czech First League',
  LIB: 'Libertadores',
  SUD: 'Sudamericana',
  CRO_1: 'Prva Hrvatska Nogometna Liga',
  CHI_1: 'CSL',
  POL_1: 'Ekstraklasa',
  NOR_1: 'Eliteserien',
  NED_1: 'Eredivisie',
  FIN_1: 'Finnliga',
  GRE_1: 'Hellas Liga',
  OZ_1: 'A-League',
  ICON: 'Icons',
  KOR_1: 'K League',
  MEX_1: 'Liga MX',
  COL_1: 'Categoría Primera A',
  POR_1: 'Primeira Liga',
  USA_1: 'MLS',
  JAP_1: 'J1 League',
  AUS_1: 'Ö. Bundesliga',
  SWI_1: 'Super League',
  ROM_1: 'Romania Liga 1',
  ARG_1: 'SAF',
  SAU_1: 'Saudi Professional League',
  SCO_1: 'SPL',
  SOUAF_1: 'South African FL',
  IRE_1: 'League of Ireland Premier Division',
  TUR_1: 'Super Lig',
  DEN_1: 'Superliga',
  UAE_1: 'UAE Gulf League',
  UKR_1: 'Ukrayinska Premier Liha',
  RUS_1: 'Russian Premier Liga',
  BRA_1: 'Liga do Brasil',
  WC14: 'World Cup 2014',
};

export const ultimateTeams = {
  HUNNSNAL: 'Hunnsnal',
  BORUSSIA: 'Borussia MunchenFlapJack',
};
